In [2]:
import numpy as np

In [3]:
matrix_default = np.array([[5.0,2.0,1.0,0.0,14], [1.0,3.0,2.0,8.0,65], [4.0,-6.0,1.0,0.0,-3], [5.0,0.0,3.0,2.0,32]], dtype=np.double)
permutation_count = 0

In [4]:
def column_max_element(column: int, matrix: np.array):
    if column < 4:
        array_col = matrix[0:4, column]
        row = np.where(abs(array_col) == max(abs(array_col)))[0][0]
        return row, column

In [5]:
def P_matrix(row_1: int, row_2: int):
    global permutation_count
    if row_1 != row_2:
        permutation_count += 1
    diagonal_matrix = np.diag([1.0, 1.0, 1.0, 1.0]).astype('double')
    diagonal_matrix[[row_1, row_2]] = diagonal_matrix[[row_2, row_1]]
    return diagonal_matrix

In [6]:
def M_matrix(column: int, matrix: np.array):
    diagonal_matrix = np.diag([1.0,1.0,1.0,1.0]).astype('double')
    main_element = matrix[column][column]
    diagonal_matrix[column][column] = 1 / main_element
    for row in range(column + 1, 4):
        diagonal_matrix[row][column] = -matrix[row][column] / main_element
    return diagonal_matrix

In [10]:
def get_inverse(matrix_def: np.array, matrix_diag: np.array):
    di = matrix_diag[:, 0]
    di_reshaped = di.reshape(4,1)
    vector_res = get_result(np.concatenate((matrix_def[:4, :4],di_reshaped), axis=1))
    matrix_solution = vector_res.reshape((4,1))
    for i in range(1,4):
        di = matrix_diag[:, i]
        di_reshaped = di.reshape(4,1)
        vector_res = get_result(np.concatenate((matrix_def[:4, :4],di_reshaped), axis=1))
        matrix_solution = np.concatenate((matrix_solution, vector_res.reshape(4,1)), axis=1)
    return matrix_solution

In [7]:
def new_matrix(column: int, matrix: np.array, diagonal_matrix = np.array([1,1,1,1])):
    max_col = column_max_element(column, matrix)

    permutation_matrix = P_matrix(max_col[0], max_col[1])

    diagon_matrix_P = np.dot(permutation_matrix, diagonal_matrix)
    matrix_P = np.dot(permutation_matrix, matrix)

    transition_matrix = M_matrix(max_col[1], matrix_P)

    diagon_matrix_new = np.dot(transition_matrix, diagon_matrix_P)
    matrix_new = np.dot(transition_matrix, matrix_P)

    return matrix_new, diagon_matrix_new, matrix_P

In [8]:
def get_determinant(permutation_count: int, matrix: np.array):
    det = pow(-1, permutation_count)
    for i in range(0,4):
        matrix, P_matrix = new_matrix(i, matrix)[0], new_matrix(i,matrix)[2]
        det *= P_matrix[i][i]
    return det

In [9]:
def get_result(matrix: np.array):
    matrix_4_4 = matrix[:4, :4]
    matrix_1_4 = matrix[:, -1]
    m, n = matrix_4_4.shape
    x_solution = np.zeros(n)
    for i in range(m-1, -1, -1):
        x_solution[i] = (matrix_1_4[i] - np.dot(matrix_4_4[i,i+1:], x_solution[i+1:])) / matrix_4_4[i,i]
    return x_solution

In [11]:
def result_high_precision():
    np.set_printoptions(precision=10, suppress=False)
    matrix = matrix_default.copy()
    diagonal_matrix = np.diag([1.0,1.0,1.0,1.0]).astype('double')
    for i in range(0,4):
        matrix, diagonal_matrix, P_matrix = new_matrix(i, matrix, diagonal_matrix)
        print(f"A:{i+1}\n", matrix)
        print(f"Diagonal_Matrix(Inverse):{i+1}\n",diagonal_matrix)
    print(f"Determinant: ",get_determinant(permutation_count, matrix_default.copy()))
    print(f"Vector_Solution: ",get_result(matrix))
    print(f"Matrix Inverse: \n", get_inverse(matrix, diagonal_matrix))

In [12]:
def result_low_precision():
    np.set_printoptions(precision=2, suppress=True)

    matrix = matrix_default.copy()
    diagonal_matrix = np.diag([1.0,1.0,1.0,1.0]).astype('double')
    for i in range(0,4):
        matrix, diagonal_matrix, P_matrix = new_matrix(i, matrix, diagonal_matrix)
        print(f"A:{i+1}\n", matrix)
        print(f"Diagonal_Matrix(Inverse):{i+1}\n",diagonal_matrix)
    print(f"Determinant: ",get_determinant(permutation_count, matrix_default.copy()))
    print(f"Vector_Solution: ",get_result(matrix))
    print(f"Matrix Inverse: \n", get_inverse(matrix, diagonal_matrix))

In [13]:
result_high_precision()

A:1
 [[  1.    0.4   0.2   0.    2.8]
 [  0.    2.6   1.8   8.   62.2]
 [  0.   -7.6   0.2   0.  -14.2]
 [  0.   -2.    2.    2.   18. ]]
Diagonal_Matrix(Inverse):1
 [[ 0.2  0.   0.   0. ]
 [-0.2  1.   0.   0. ]
 [-0.8  0.   1.   0. ]
 [-1.   0.   0.   1. ]]
A:2
 [[ 1.0000000000e+00  4.0000000000e-01  2.0000000000e-01  0.0000000000e+00
   2.8000000000e+00]
 [ 0.0000000000e+00  1.0000000000e+00 -2.6315789474e-02  0.0000000000e+00
   1.8684210526e+00]
 [ 0.0000000000e+00  0.0000000000e+00  1.8684210526e+00  8.0000000000e+00
   5.7342105263e+01]
 [ 0.0000000000e+00 -2.2204460493e-16  1.9473684211e+00  2.0000000000e+00
   2.1736842105e+01]]
Diagonal_Matrix(Inverse):2
 [[ 0.2           0.            0.            0.          ]
 [ 0.1052631579  0.           -0.1315789474  0.          ]
 [-0.4736842105  1.            0.3421052632  0.          ]
 [-0.7894736842  0.           -0.2631578947  1.          ]]
A:3
 [[ 1.0000000000e+00  4.0000000000e-01  2.0000000000e-01  0.0000000000e+00
   2.800000

In [14]:
result_low_precision()

A:1
 [[  1.    0.4   0.2   0.    2.8]
 [  0.    2.6   1.8   8.   62.2]
 [  0.   -7.6   0.2   0.  -14.2]
 [  0.   -2.    2.    2.   18. ]]
Diagonal_Matrix(Inverse):1
 [[ 0.2  0.   0.   0. ]
 [-0.2  1.   0.   0. ]
 [-0.8  0.   1.   0. ]
 [-1.   0.   0.   1. ]]
A:2
 [[ 1.    0.4   0.2   0.    2.8 ]
 [ 0.    1.   -0.03  0.    1.87]
 [ 0.    0.    1.87  8.   57.34]
 [ 0.   -0.    1.95  2.   21.74]]
Diagonal_Matrix(Inverse):2
 [[ 0.2   0.    0.    0.  ]
 [ 0.11  0.   -0.13  0.  ]
 [-0.47  1.    0.34  0.  ]
 [-0.79  0.   -0.26  1.  ]]
A:3
 [[ 1.    0.4   0.2   0.    2.8 ]
 [ 0.    1.   -0.03  0.    1.87]
 [ 0.   -0.    1.    1.03 11.16]
 [ 0.    0.    0.    6.08 36.49]]
Diagonal_Matrix(Inverse):3
 [[ 0.2   0.    0.    0.  ]
 [ 0.11  0.   -0.13  0.  ]
 [-0.41  0.   -0.14  0.51]
 [ 0.28  1.    0.59 -0.96]]
A:4
 [[ 1.    0.4   0.2   0.    2.8 ]
 [ 0.    1.   -0.03  0.    1.87]
 [ 0.   -0.    1.    1.03 11.16]
 [ 0.    0.    0.    1.    6.  ]]
Diagonal_Matrix(Inverse):4
 [[ 0.2   0.    0.    0.  